### ISSUE TITLE
High load CPU

### ISSUE THREAD

**Issue by klimentyev** [hoffstadt/mvThreadPool#2]
I see very high CPU load for current version of thread pool. I run example with 30 sec sleep. All time I had 100% load for my 8 logical threads.
I can see by profiling that lock and unlock of mutex spent a long of time (almost all CPU time) even task sleeps.

**Comment by klimentyev** [comment]
I added a `std::this_thread::sleep_for(std::chrono::seconds(10));` to https://github.com/hoffstadt/mvThreadPool/blob/f9f49dd2cdc9af8a89343812c2f022ebfcb58c9b/main.cpp#L34
and saw CPU usage.
I have 100% load CPU before task submitting too.

**Comment by klimentyev** [comment]
I see the reason. You use active waiting by while loop and yeield. Unfortunately, I can't this implementation due too high CPU load. I'll rewrite it to use mutex and conditional variable for waiting procedure.

**Comment by hoffstadt** [comment]
Sorry I’ve been away. Will respond fully in a few hours!

**Comment by klimentyev** [comment]
@hoffstadt tnx! In my application, there are many long high load tasks, so using of mutex with cond. variable is more preferably.
Your implementation is very beautiful, but it is good for very short tasks where time 
of switch between context is very expensive.
And I can't use it for singleton that should be wait of tasks a lot of time.
